# -*- coding: utf-8 -*-
"""Data Cleaning dan Prepop .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-MmQZLBQIdaw_hN4IUfVd-bRN1uszG4r
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_excel('/content/drive/MyDrive/capstone_minatku/12QuestionRiasec.xlsx', engine = 'openpyxl')
df.head(n = 5)

df = df.drop(columns=['Unnamed: 13', 'Pertanyaan Riasec'])

df.head(5)

# #RENAME COLUMN

df.rename(columns = {'Menguji kualitas komponen sebelum pengiriman':'Q1',
                     'Bekerja di anjungan pengeboran minyak lepas pantai':'Q2',
                     'Mempelajari struktur tubuh manusia':'Q3',
                     'Mempelajari perilaku hewan':'Q4',
                     'Memimpin paduan suara musik':'Q5',
                     'Menyutradarai sebuah drama':'Q6',
                     'Memberikan bimbingan karir kepada orang-orang':'Q7',
                     'Melakukan pekerjaan sukarela di organisasi':'Q8',
                     'Menjual waralaba restoran kepada perorangan':'Q9',
                     'Menjual barang dagangan di toserba':'Q10',
                     'Membuat cek gaji bulanan untuk sebuah kantor':'Q11',
                     'Menggunakan program komputer untuk menghasilkan tagihan pelanggan':'Q12',}, inplace = True)

df.head(5)

#MAKING NEW COLUMNS

#Q1
df['R1'] = df['Q1'].replace(['Dislike','Enjoy','Neutral'],['0','1','2']).astype(int)
#Q2
df['R2'] = df['Q2'].replace(['Dislike','Enjoy','Neutral'],['0','1','2']).astype(int)
#Q3
df['I1'] = df['Q3'].replace(['Dislike','Enjoy','Neutral'],['0','1','2']).astype(int)
#Q4
df['I2'] = df['Q4'].replace(['Dislike','Enjoy','Neutral'],['0','1','2']).astype(int)
#Q5
df['A1'] = df['Q5'].replace(['Dislike','Enjoy','Neutral'],['0','1','2']).astype(int)
#Q6
df['A2'] = df['Q6'].replace(['Dislike','Enjoy','Neutral'],['0','1','2']).astype(int)
#Q7
df['S1'] = df['Q7'].replace(['Dislike','Enjoy','Neutral'],['0','1','2']).astype(int)
#Q8
df['S2'] = df['Q8'].replace(['Dislike','Enjoy','Neutral'],['0','1','2']).astype(int)
#Q9
df['E1'] = df['Q9'].replace(['Dislike','Enjoy','Neutral'],['0','1','2']).astype(int)
#Q10
df['E2'] = df['Q10'].replace(['Dislike','Enjoy','Neutral'],['0','1','2']).astype(int)
#Q11
df['C1'] = df['Q11'].replace(['Dislike','Enjoy','Neutral'],['0','1','2']).astype(int)
#Q12
df['C2'] = df['Q12'].replace(['Dislike','Enjoy','Neutral'],['0','1','2']).astype(int)

df.head(5)

# # #MAPPING
# df['R1'] = df['Q1'].map(df['Q1'].unique().tolist().index).astype(int)
# df['R2'] = df['Q2'].map(df['Q2'].unique().tolist().index).astype(int)
# df['I1'] = df['Q3'].map(df['Q3'].unique().tolist().index).astype(int)
# df['I2'] = df['Q4'].map(df['Q4'].unique().tolist().index).astype(int)
# df['A1'] = df['Q5'].map(df['Q5'].unique().tolist().index).astype(int)
# df['A2'] = df['Q6'].map(df['Q6'].unique().tolist().index).astype(int)
# df['S1'] = df['Q7'].map(df['Q7'].unique().tolist().index).astype(int)
# df['S2'] = df['Q8'].map(df['Q8'].unique().tolist().index).astype(int)
# df['E1'] = df['Q9'].map(df['Q9'].unique().tolist().index).astype(int)
# df['E2'] = df['Q10'].map(df['Q10'].unique().tolist().index).astype(int)
# df['C1'] = df['Q11'].map(df['Q11'].unique().tolist().index).astype(int)
# df['C2'] = df['Q12'].map(df['Q12'].unique().tolist().index).astype(int)

df = df.drop(columns=['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11', 'Q12'])

df.head(5)

df.dtypes

from google.colab import files
df.to_csv('RIASEC10Q.csv')
files.download("RIASEC12Q.csv")